[package]
name = "vsss-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.4", features = ["rand"] }
num-prime = "0.4.3"
sha2 = "0.9"
rand = "0.8"
num-traits = "0.2"
